version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: traductor-es-pt-br_api_1
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
      - minio
