version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - PYTHONPATH=/app
    command: ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "celery", "-A", "app.worker_task", "worker", "--loglevel=info"]
    volumes:
      - ./data:/data
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app
