api:
  build: .
  volumes:
    - ./data:/data
  ports:
    - "8000:8000"
  depends_on:
    - redis
    - minio
  environment:
    - CELERY_BROKER=redis://redis:6379/0
  command: uvicorn api:app --host 0.0.0.0 --port 8000
