version: "3.9"

services:
  redis:
    image: redis:7
    container_name: traductor-es-pt-br_redis_1
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: traductor-es-pt-br_minio_1
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: traductor-es-pt-br_api_1
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
      - minio
    environment:
      - CELERY_BROKER=redis://redis:6379/0

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: traductor-es-pt-br_worker_1
    command: ["python", "-m", "celery", "-A", "app.worker_task", "worker", "--loglevel=info"]
    volumes:
      - ./app:/app
    depends_on:
      - redis
