version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # WebUI
    volumes:
      - minio_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
    environment:
      UPLOAD_DIR: /data/uploads
      OUT_DIR: /data/out
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/out:/data/out
    command: ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/out:/data/out
    command: ["celery", "-A", "app.worker_task", "worker", "--loglevel=info"]

volumes:
  minio_data:
